### ISSUE TITLE
Arduino code clean-up

### ISSUE THREAD

**Issue by shashsuresh** [IndTechSpprt/Split_inference_microcontrollers_fork#9]
* Smaller functions
* Smaller files
* Reduce sources of subtle bugs

**Comment by IndTechSpprt** [comment]
# Some factors to consider

* Store lengths rather than passing them around over serial (will help from automation perspective)
* Smaller functions
* Smaller files
* Reduce sources of subtle bugs

**Comment by shashsuresh** [comment]
Approach (consider splitting up task into smaller ones):
1. General clean-up
3. Store `coor_lines` and `lines` in a file
4. Download `input_length` and `result_length` into files after (#12 ) is done
5. Better protocol description

**Comment by shashsuresh** [comment]
`download` doesn't seem to work correctly (`lines` and `coor_lines` do not have the correct values) post refactoring. 

Investigate if it is related to the code or the procedure.
